# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8d0544d2c76498f20b68c560cb6305fb3cd0c94c8d16a0f67e4120b2da69e72584d9c4f230583cf6cf19bae9e7b8ec30c2b0f738a947e768c466ca24a82a3af

test:
  secret_key_base: 8d24fa541457110e22abe924b2c1f2a78fff8d5494836b464c163608c42e2160b6af8aa5bea671658a5c73cdd3a7ad06a76afec1b9144403724765738abe28b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
